spring.application.name=ApiGateway
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

spring.cloud.gateway.routes[0].id=RegisterRoute
spring.cloud.gateway.routes[0].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/register/**

spring.cloud.gateway.routes[1].id=UserService
spring.cloud.gateway.routes[1].uri=lb://USERSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/userinfo/**

spring.cloud.gateway.routes[2].id=AuthService
spring.cloud.gateway.routes[2].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**


spring.cloud.gateway.default-filters[0]=SaveSession

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true